image: docker:stable

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - pip3 install docker-compose
  - pip3 install docker-auto-labels

stages:
  - test

tests:
  stage: test
  script:
    - sh ./scripts/test.sh
  tags:
    - test
